#!/bin/bash

##
# Build wrapper script for running locally.
#

ENV=$1
shift

function usage() {
  echo "Usage:"
  echo "./tflocal <env> terraform <terraform operation + options>"
  echo "Note: This script will run any command that comes after the <env> argument."
  echo "Example:"
  echo "./tflocal <env> terraform plan"
  echo "./tflocal <env> terraform init -reconfigure"
}

if [[ -z "${ENV}" ]]
then
  usage
  exit 1
fi

ENV_DIR="env/$ENV"
if [[ ! -d "$ENV_DIR" ]]
then
  echo "No environment dir $ENV_DIR found."
  exit 1
fi

if [[ "$@" =~ "destroy" ]]
then
  read -p "It looks like you are about to destroy the \"$ENV\" environment - are you sure??? (yes/no): " confirm
  if [[ "$confirm" != "yes" ]]
  then
    exit 0
  fi
fi

#
# Symlink stuff from the env.
#
for tf_file in $ENV_DIR/*.tf*
do
  echo "ln -s $tf_file"
  ln -s $tf_file
done

if [[ "$@" =~ "init" ]]
then
  echo "rm -rf .terraform .terraform.lock.hcl"
  rm -rf .terraform .terraform.lock.hcl
fi


#
# Run the thing
#
"$@"
rval=$?

#
# Cleanup
#
echo "Cleaning up."
for lnk in $(find . -maxdepth 1 -type l)
do
  echo "rm $lnk"
  rm -f $lnk
done
exit $rval